server:
  port: 9000
  
spring:
  application:
    name: erueka
  
eureka:
  instance:
    hostname: eureka-server   #eureka实例的主机名
  client:
    fetch-registry: true  #不从eureka上获取服务的注册信息
    register-with-eureka: true #把自己注册到eureka上
    service-url:
      defaultZone: http://localhost:9100/eureka/ ,http://localhost:9200/eureka/  #注册中心地址
       